apiVersion: apps/v1
kind: Deployment
metadata:
  name: cstarmstemplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cstarmstemplate
  template:
    metadata:
      labels:
        app: cstarmstemplate
    spec:
      containers:
        - name: cstarmstemplate
          image: cstarmstemplate
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
#          envFrom:
#            - configMapRef:
#                name: cstarmstemplate
#             - secretRef:
#                 name: application-insights
#             - secretRef:
#                 name: rtd-blob-storage-events
#             - secretRef:
#                 name: rtd-internal-api
#            - secretRef:
#                name: mongo-credentials
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 50m
              memory: 256Mi



